apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khaos-monkey-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["pods", "namespaces"]
  verbs: ["list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: khaos-monkey-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: khaos-monkey
roleRef:
  kind: ClusterRole
  name: khaos-monkey-cluster-role
  apiGroup: ""