name: Update "khaos-monkey"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/cicd-khaos-monkey.yml'
      - 'Cargo.*'
      - 'Dockerfile'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/cicd-khaos-monkey.yml'
      - 'Cargo.*'
      - 'Dockerfile'

concurrency: 
  group: "khaos-monkey"
  cancel-in-progress: true

env:
  APP-VERSION: ${{ github.run_id }}

jobs:
  build:
    environment: stage
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./khaos-monkey
        push: true
        tags: dagandersen/khaos-monkey:${{ env.APP-VERSION }}
